
<!-- --- -->
<!-- title: 'Reproducible Research: Peer Assessment 1' -->
<!-- output: -->
<!--   html_document: -->
<!--     keep_md: yes -->

<!-- --- -->


<!-- Start -->
```{r echo=TRUE}

library(knitr)
library(dplyr)
library(ggplot2)
# opts_chunk$set(echo = TRUE)

setwd("C:\\DS\\Week2\\RepData_PeerAssessment1-master")
```

Loading/ preprocessing the data
```{r echo=TRUE}
dr<- read.csv('activity.csv')
activity_data <- dr[ with (dr, { !(is.na(steps)) } ), ]
```

What is the mean total number of steps taken per day?
```{r echo=TRUE}
activity_data_by_day <- group_by(activity_data, date)
stepsByDay <- summarise(activity_data_by_day, total = sum(steps))
stepsByDay
```

```{r echo=TRUE}
hist(stepsByDay$total, main="Total steps per day", 
     xlab="Total steps in a day",col="green")
summary(stepsByDay)
```

What is the average daily activity pattern?
```{r echo=TRUE}
stepsByInterval <- aggregate(steps ~ interval, activity_data, mean)

plot(stepsByInterval$interval, stepsByInterval$steps, type='l', 
     main="Avg steps - all days", xlab="Interval", 
     ylab="Avg steps")
```    

```{r echo=TRUE}

Maximum_steps_no <- which.max(stepsByInterval$steps)

stepsByInterval[Maximum_steps_no, ]
```

Impute missing values
```{r echo=TRUE}

sum(is.na(dr))

da_imputed <- dr
for (i in 1:nrow(da_imputed)) {
  if (is.na(da_imputed$steps[i])) {
    interval <- da_imputed$interval[i]
    steps <- stepsByInterval[
      stepsByInterval$interval == interval,]
    da_imputed$steps[i] <- steps$steps
  }
}

impStepByDday <- aggregate(steps ~ date, da_imputed, sum)
head(impStepByDday)

hist(impStepByDday$steps, main="Total No. of steps / day (imputed)", 
     xlab="Total #  of steps per day")
     
mean(impStepByDday$steps)
median(impStepByDday$steps)
mean(stepsByDay$total)
median(stepsByDay$total)
```

Are there differences in activity patterns between weekdays and weekends?
```{r echo=TRUE}
WeekDay <- function(date_val) {
    wd <- weekdays(as.Date(date_val, '%Y-%m-%d'))
    if  (!(wd == 'Saturday' || wd == 'Sunday')) {
        rtn <- 'Weekday'
    } else {
        rtn <- 'Weekend'
    }
    rtn
}
```

<!-- # Apply the week_day function and add a new column to activity dataset -->
<!-- # generating aggregated data frame  -->
Showing the chart
```{r echo=TRUE}
dr$day_type <- as.factor(sapply(dr$date, WeekDay))


stepsPerDayImpute <- aggregate(steps ~ interval+day_type, dr, mean)


chrt <- ggplot(stepsPerDayImpute, aes(interval, steps)) +
    geom_line(stat = "identity", aes(colour = day_type)) +
    theme_gray() +
    facet_grid(day_type ~ ., scales="fixed", space="fixed") +
    labs(x="Interval", y=expression("No of Steps")) +
    ggtitle("# of steps/Interval by daytype")

print(chrt)
```


